services:
  app:
    build: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "9228:9228" # For debugger
    env_file:
      - .env
    command: bash -c "npm install && npm run watch"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  postgres:
    image: postgres:18
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  node_modules:
